#; Audio Effects definitions
#;[EffectName]
#; resource=[resource name -- see resources.ini]
#; loop=[1,0]
#; positional=[1,0]
#; type=[music,cue,ui,high_event,event,ambiance] -- priority in that order
#; gain=[0,infinity] -- optional


#
[MenuMusic]
resource=ThisCouldBeIt
loop=1
positional=0
type=music
gain=0.9
preload=1

[Level1Music]
resource=LucyAddsBlubber
loop=1
positional=0
type=music
gain=0.6
preload=1

#
# CUES VO
#
[AngelFlagTaken]
resource=AngelFlagTaken
loop=0
positional=0
type=cue
gain=1.033
preload=1

[DemonFlagTaken]
resource=DemonFlagTaken
loop=0
positional=0
type=cue
gain=1.033
preload=1

[AngelScore]
resource=AngelScore
loop=0
positional=0
type=cue
gain=1.033
preload=1

[DemonScore]
resource=DemonScore
loop=0
positional=0
type=cue
gain=1.033
preload=1

#
# PLAYER VO
#
[CelebrateVO1]
resource=CelebrateVO1
loop=0
positional=0
type=cue
gain=1.1
preload=1

[CelebrateVO2]
resource=CelebrateVO2
loop=0
positional=0
type=cue
gain=0.8
preload=1

[CelebrateVO3]
resource=CelebrateVO3
loop=0
positional=0
type=cue
gain=0.8
preload=1

[DeathSelfVO]
resource=DeathSelfVO
loop=0
positional=0
type=cue
gain=0.8
preload=1

[DeathSelfVO2]
resource=DeathSelfVO2
loop=0
positional=0
type=cue
gain=1.1
preload=1

[DeathSelfVO3]
resource=DeathSelfVO3
loop=0
positional=0
type=cue
gain=1.1
preload=1

[DeathSelfVO4]
resource=DeathSelfVO4
loop=0
positional=0
type=cue
gain=1.1
preload=1

[KilledSomeoneVO]
resource=KilledSomeoneVO
loop=0
positional=0
type=cue
gain=0.8
preload=1

[KilledSomeoneVO2]
resource=KilledSomeoneVO2
loop=0
positional=0
type=cue
gain=0.8
preload=1

[KilledSomeoneVO3]
resource=KilledSomeoneVO2
loop=0
positional=0
type=cue
gain=0.8
preload=1

#
# PLAYER
#
[Death3D]
resource=PlayerHit
loop=0
positional=1
type=high_event
gain=9.4
preload=1

[DeathSelf]
resource=PlayerSelfDeath
loop=0
positional=0
type=cue
gain=0.8
preload=1

[JumpSelf1]
resource=Jump1VO
loop=0
positional=0
type=cue
gain=0.5
preload=1

[JumpSelf2]
resource=Jump2VO
loop=0
positional=0
type=cue
gain=0.5
preload=1

[JumpSelf3]
resource=Jump3VO
loop=0
positional=0
type=cue
gain=0.6
preload=1

[Spawn]
resource=WorldPlayerSpawn
loop=0
positional=1
gain=7.4
type=event
preload=1

[SpawnCountdown]
resource=SpawnCountdownCue
loop=0
positional=0
gain=2.0
type=cue
preload=1

[Whistle]
resource=CueWhistle
loop=0
positional=0
type=cue
gain=3.7
preload=1

#
# BLOCK SFX
#
[ThrowBlock3D]
resource=PlayerBlockToss
loop=0
positional=1
type=event
preload=1
gain=4.4

[AddBlockToPouchUI]
resource=CuePickupBlock
loop=0
positional=0
type=cue
gain=0.5
preload=1

[AddBlockToFullPouch]
resource=CuePouchFull
loop=0
positional=0
type=cue
gain=0.3
preload=1

[CollisionSlow]
resource=WorldBlockHit
loop=0
positional=1
type=event
gain=2.4
preload=1

[CollisionMed]
resource=WorldBlockHit
loop=0
positional=1
type=event
gain=3.6
preload=1

[CollisionFast]
resource=WorldBlockHit
loop=0
positional=1
type=event
gain=5.2
preload=1

[CollisionPlayer]
resource=PlayerHit
loop=0
positional=1
type=high_event
gain=2.0
preload=1


#
# BOMB
#
[Explosion]
resource=Explosion
loop=0
positional=1
type=high_event
gain=250.0
preload=1

[BoomVO]
resource=BoomVO
loop=0
positional=1
type=high_event
gain=100.0
preload=1

[BoomVO2]
resource=BoomVO2
loop=0
positional=1
type=high_event
gain=100.0
preload=1

[BombSpawn]
resource=WorldBombSpawn
loop=0
positional=1
type=event
gain=3.0
preload=1

#
# FLAG
#
[FlagCapFriendly]
resource=CueFlagScoreFriendly
loop=0
positional=0
type=cue
gain=0.8
preload=1wwwwww

[FlagCapEnemy]
resource=CueFlagScoreEnemy
loop=0
positional=0
type=cue
gain=0.8
preload=1

[FlagCap3D]
resource=CueFlagScoreWorld
loop=0
positional=1
type=high_event
preload=1

[FlagRecover3D]
resource=WorldFlagRecovered
loop=0
positional=1
type=high_event
preload=1

[FlagAutoRecover3D]
resource=WorldFlagRecovered
loop=0
positional=1
type=high_event
preload=1

[FlagSpawn3D]
resource=WorldFlagSpawn
loop=0
positional=1
type=event
preload=1

#
# SPEECH BUBBLE
#
[SpeechBubblePopupTutorial]
resource=CueSpeechBubble
loop=0
positional=1
type=event
gain=4.9
preload=1

[SpeechBubblePopup]
resource=CueSpeechBubble
loop=0
positional=1
type=event
gain=1.2
preload=1

#
# MENU SFX
#
[UIMouseOver]
resource=UiHover
loop=0
positional=0
type=ui
gain=1.0
preload=1

[UIMouseOut]
resource=UiOut
loop=0
positional=0
type=ui
gain=0.3
preload=1

[UIMouseClick]
resource=UiClick
loop=0
positional=0
type=ui
gain=0.7
preload=1

[Toblo1]
resource=Toblo1
loop=0
positional=0
type=ui
gain=2.5
preload=1

[Toblo2]
resource=Toblo2
loop=0
positional=0
type=ui
gain=2.5
preload=1


# jjensen
