# Sound files config file
# [ResourceName]
# type=[wav,ogg]
# filename=[filename of sound file]

[LucyAddsBlubber]
type=ogg
filename=Sfx\music\Lucy Adds Blubber.ogg

[ThisCouldBeIt]
type=ogg
filename=Sfx\music\This Could Be It.ogg

[AngelFlagTaken]
type=wav
filename=Sfx\announcements\aFlagTaken2.wav

[DemonFlagTaken]
type=wav
filename=Sfx\announcements\dFlagTaken3.wav

[AngelScore]
type=wav
filename=Sfx\announcements\aScore2.wav

[DemonScore]
type=wav
filename=Sfx\announcements\dScore3.wav

[CelebrateVO1]
type=wav
filename=Sfx\player_voice\woohoo1.wav

[CelebrateVO2]
type=wav
filename=Sfx\player_voice\yay1.wav

[CelebrateVO3]
type=wav
filename=Sfx\player_voice\yess1.wav

[Jump1VO]
type=wav
filename=Sfx\player_voice\jump1.wav

[Jump2VO]
type=wav
filename=Sfx\player_voice\jump2.wav

[Jump3VO]
type=wav
filename=Sfx\player_voice\jump4.wav

[DeathSelfVO]
type=wav
filename=Sfx\player_voice\ow2.wav

[DeathSelfVO2]
type=wav
filename=Sfx\player_voice\ohno2.wav

[DeathSelfVO3]
type=wav
filename=Sfx\player_voice\shucks1.wav

[DeathSelfVO4]
type=wav
filename=Sfx\player_voice\eep2.wav

[KilledSomeoneVO]
type=wav
filename=Sfx\player_voice\got1.wav

[KilledSomeoneVO2]
type=wav
filename=Sfx\player_voice\tt2.wav

[KilledSomeoneVO3]
type=wav
filename=Sfx\player_voice\haha1.wav

[BoomVO]
type=wav
filename=Sfx\player_voice\boom4.wav

[BoomVO2]
type=wav
filename=Sfx\player_voice\kaboom1.wav

[Toblo1]
type=wav
filename=Sfx\ui\toblo1.wav

[Toblo2]
type=wav
filename=Sfx\ui\toblo2.wav


[CuePickupBlock]
type=wav
filename=Sfx\cue\pickup_block.wav

[CuePouchFull]
type=wav
filename=Sfx\cue\pouch_full.wav

[CueWhistle]
type=wav
filename=Sfx\cue\whistle.wav

[CueFlagScoreWorld]
type=wav
filename=Sfx\world_sounds\flag_captured_3d.wav

[CueFlagScoreFriendly]
type=wav
filename=Sfx\cue\flag_capture_friendly.wav

[CueFlagScoreEnemy]
type=wav
filename=Sfx\cue\flag_capture_enemy.wav

[CueSpeechBubble]
type=wav
filename=Sfx\cue\speech_bubble.wav

[PlayerHit]
type=wav
filename=Sfx\player\block_hit2.wav

[PlayerBlockToss]
type=wav
filename=Sfx\player\block_toss.wav

[PlayerSelfDeath]
type=wav
filename=Sfx\player\self_death.wav

[UiClick]
type=wav
filename=Sfx\ui\click.wav

[UiHover]
type=wav
filename=Sfx\ui\hover.wav

[UiOut]
type=wav
filename=Sfx\ui\out.wav

[Explosion]
type=wav
filename=Sfx\world_sounds\bomb.wav

[WorldBombSpawn]
type=wav
filename=Sfx\world_sounds\bomb_spawn.wav

[WorldFlagRecovered]
type=wav
filename=Sfx\world_sounds\flag_recovered_3d.wav

[WorldPlayerSpawn]
type=wav
filename=Sfx\world_sounds\player_spawn.wav

[SpawnCountdownCue]
type=wav
filename=Sfx\cue\spawn_countdown.wav

[WorldBlockHit]
type=wav
filename=Sfx\world_sounds\block_hit.wav

[WorldFlagSpawn]
type=wav
filename=Sfx\world_sounds\flag_spawn.wav

# jjensen