import { VARIANT_TO_BASE_ID } from "./characterSizes.js";
import { characterName, isJPOriginal12 } from "./lookups.js";

/**
 * Filenames for public/characters/*.svg (generated by
 * scripts/generateCharacterSvgs.ts from the renderer's own polygon-drawing
 * methods, via `npm run generate:character-svgs`) - one icon per base
 * fighter, not per variant.
 */
const CHARACTER_ICON_FILENAMES: Partial<Record<number, string>> = {
  0x00: "mario",
  0x01: "fox",
  0x02: "donkey_kong",
  0x03: "samus",
  0x04: "luigi",
  0x05: "link",
  0x06: "yoshi",
  0x07: "captain_falcon",
  0x08: "kirby",
  0x09: "pikachu",
  0x0a: "jigglypuff",
  0x0b: "ness",
};

/**
 * URL for a character's icon. Variant IDs (Polygon/Metal/Giant/JP/EU - see
 * characterSizes.ts's VARIANT_TO_BASE_ID) resolve to their base fighter's
 * icon - there's only one icon per fighter, not per variant. A JP variant
 * still gets the same icon as its NA counterpart; characterName() already
 * distinguishes them in text (e.g. "Mario" vs. "Mario (JP)"), so the icon
 * doesn't need to.
 *
 * Returns undefined for characters with no icon (e.g. Master Hand) - a
 * caller with no fallback should just skip rendering an icon in that case.
 */
export function characterIconUrl(characterId: number): string | undefined {
  const resolvedId = VARIANT_TO_BASE_ID[characterId] ?? characterId;
  const filename = CHARACTER_ICON_FILENAMES[resolvedId];
  return filename
    ? `${import.meta.env.BASE_URL}characters/${filename}.svg`
    : undefined;
}

/**
 * Icon markup for a character, meant to replace a plain text name in
 * compact UI (game list rows, dropdowns, etc.) - an `<img>` (alt/title set
 * to the full name, e.g. "Mario (JP)", for accessibility and hover) plus a
 * visible "(JP)" badge for Japanese-region variants, since the icon alone
 * can't otherwise distinguish "Mario" from "Mario (JP)".
 *
 * characterName()'s output is always one of a small fixed set of known
 * strings from a static lookup table (never user-provided data), so it's
 * safe to interpolate directly into the returned HTML without escaping.
 *
 * Falls back to the plain character name (no markup) if there's no icon
 * for this character (e.g. Master Hand).
 */
export function characterIconHtml(
  characterId: number,
  className = "char-icon",
): string {
  const url = characterIconUrl(characterId);
  const label = characterName(characterId);
  if (!url) return label;

  const jpBadge = isJPOriginal12(characterId)
    ? `<span class="char-icon-jp-badge">(JP)</span>`
    : "";
  return `<img class="${className}" src="${url}" alt="${label}" title="${label}" />${jpBadge}`;
}
